import React, { useEffect, useState } from 'react';

interface AnalystNoteProps {
  symbol: string;
}

export default function AnalystNote({ symbol }: AnalystNoteProps) {
  const [loading, setLoading] = useState(false);
  const [note, setNote] = useState<string | null>(null);

  useEffect(() => {
    setNote(null);
  }, [symbol]);

  const fetchNote = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}/api/analysis/${symbol}`, { method: 'POST' });
      if (!res.ok) throw new Error("Failed to fetch analysis");
      const data = await res.json();
      setNote(data.narrative);
    } catch (e) {
      setNote("Analyst note unavailable at this time.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-panel border border-brass/30 bg-brass/5 rounded-xl p-5 mt-5">
      <div className="flex justify-between items-center mb-3">
        <div className="font-display font-extrabold text-xs tracking-[1px] text-brass">
          ANALYST NOTE
        </div>
        <button 
          onClick={fetchNote} 
          disabled={loading}
          className="font-mono text-[10px] bg-brass/20 text-brass px-2.5 py-1 rounded hover:bg-brass/30 transition-colors disabled:opacity-50"
        >
          {loading ? "Generating..." : note ? "Refresh Note" : "Generate Note"}
        </button>
      </div>
      
      {loading ? (
        <div className="animate-pulse flex flex-col gap-2">
          <div className="h-3 bg-panel-raised rounded w-full"></div>
          <div className="h-3 bg-panel-raised rounded w-[90%]"></div>
          <div className="h-3 bg-panel-raised rounded w-[95%]"></div>
          <div className="h-3 bg-panel-raised rounded w-[60%]"></div>
        </div>
      ) : note ? (
        <div className="font-body text-[13px] leading-relaxed text-ink-muted">
          {note}
        </div>
      ) : (
        <div className="font-body text-[13px] text-ink-muted/50 italic text-center py-6">
          Click the button above to generate an AI analysis for this stock.
        </div>
      )}

      <div className="mt-4 pt-3 border-t border-brass/20 font-body text-[10px] text-ink-muted/70 italic">
        Generated by Llama 3.3 (via Groq) from the signal data above — not an independent prediction.
      </div>
    </div>
  );
}
